[lr]
    mode = "composer"
    value = 1.0
    end = 2000
    [[lr.schedules]]
        end = 0.25
        warmup = 100
        mode = "constant"
        value = 0.5
    [[lr.schedules]]
        end = 0.5
        mode = "cosine"
        warmup = 50
        value = 1
        min_value = 0.01
    [[lr.schedules]]
        end = 0.75
        warmup = 50
        value = 1
        min_value = 0.01
        mode = "polynomial"
        power = 2
    [[lr.schedules]]
        end = 1.0
        warmup = 50
        value = 1
        min_value = 0.01
        mode = "step"
        gamma = 0.8
        step_size = 50

[weight_decay]
    mode = "composer"
    value = 1.0
    [[weight_decay.schedules]]
        end = 500
        warmup = 100
        mode = "constant"
        value = 0.5
    [[weight_decay.schedules]]
        end = 1000
        mode = "cosine"
        warmup = 50
        value = 1
        min_value = 0.01
    [[weight_decay.schedules]]
        end = 1500
        warmup = 50
        value = 1
        min_value = 0.01
        mode = "polynomial"
        power = 2
    [[weight_decay.schedules]]
        end = 2000
        warmup = 50
        value = 1
        min_value = 0.01
        mode = "step"
        gamma = 0.8
        step_size = 50

